# Generated by Django 4.2.3 on 2023-07-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier', '0002_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, null=True)),
                ('expected_arrival', models.CharField(max_length=200, null=True)),
                ('usps', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('delivery', models.CharField(max_length=200, null=True)),
                ('package_name', models.CharField(max_length=200, null=True)),
                ('order_date', models.CharField(max_length=200, null=True)),
                ('delivery_date', models.CharField(max_length=200, null=True)),
                ('reciever_name', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
