# Generated by Django 4.2.3 on 2023-07-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_step6_step5_step4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_pic',
            field=models.ImageField(blank=True, default='ship.jpg', null=True, upload_to=''),
        ),
    ]
