# Generated by Django 4.2.3 on 2023-07-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_rename_img_product_profile_pic_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
