# Generated by Django 4.2.3 on 2023-07-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_product_address_product_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='product',
            name='postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
