# Generated by Django 4.2.3 on 2023-07-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_rename_location_product_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
