# Generated by Django 4.2.3 on 2023-07-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0011_product_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
