# Generated by Django 4.2.3 on 2023-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0012_product_shipping_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step5',
            name='user',
        ),
        migrations.RemoveField(
            model_name='step6',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='method_of_payment',
            field=models.CharField(default='Mastercard', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.CharField(default='International', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Step4',
        ),
        migrations.DeleteModel(
            name='Step5',
        ),
        migrations.DeleteModel(
            name='Step6',
        ),
    ]
