# Generated by Django 4.2.3 on 2023-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0014_product_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='12.5Kg', max_length=200, null=True),
        ),
    ]
