# Generated by Django 4.2.3 on 2023-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0016_alter_tracking_fifth_step_alter_tracking_first_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
