# Generated by Django 4.2.3 on 2023-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0017_customer_name_product_name_tracking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='movement',
            field=models.CharField(default='Hold', max_length=200, null=True),
        ),
    ]
