# Generated by Django 5.2 on 2025-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0019_remove_product_profile_pic_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carrier_reference_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='depature_time',
            field=models.CharField(default='Processing', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pick_up_time',
            field=models.CharField(default='Processing', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quanity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_flight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
