# Generated by Django 5.2 on 2025-04-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0020_product_carrier_reference_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expected_arrival',
            new_name='pick_up_date',
        ),
    ]
