# Generated by Django 5.2 on 2025-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0022_rename_first_step_tracking_arrived_at_local_delivery_hub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='fifth_step',
            new_name='ready_for_delivery',
        ),
        migrations.RenameField(
            model_name='tracking',
            old_name='in_transit_to_sorting_facility',
            new_name='sorting_facility',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='sixth_step',
        ),
        migrations.AddField(
            model_name='tracking',
            name='picked_up_by_courier',
            field=models.CharField(default='Picked Up by Courier', max_length=200, null=True),
        ),
    ]
