# Generated by Django 5.2 on 2025-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0023_rename_fifth_step_tracking_ready_for_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='order_placed',
            field=models.CharField(choices=[('Processing...', 'Processing...'), ('Order Has Been Placed', 'Order Has Been Placed')], default='Order Has Been Placed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='picked_up_by_courier',
            field=models.CharField(choices=[('Processing...', 'Processing...'), ('Order Has Been Picked Uo For Delivery', 'Order Has Been Picked Uo For Delivery')], default='Picked Up by Courier', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='sorting_facility',
            field=models.CharField(choices=[('Processing...', 'Processing...'), ('Order Has Been Sorted', 'Order Has Been Sorted')], default='Processing...', max_length=200, null=True),
        ),
    ]
